#!/bin/bash

ACTIVE_WINDOW_PID=$()
FOCUS=""
DIRECTION_LEFT=""
DIRECTION_RIGHT=""
DIRECTION_UP=""
DIRECTION_DOWN=""
DIRECTION=""

case "$1" in
"$DIRECTION_LEFT") DIRECTION="h" ;;
"$DIRECTION_RIGHT") DIRECTION="l" ;;
"$DIRECTION_UP") DIRECTION="k" ;;
"$DIRECTION_DOWN") DIRECTION="j" ;;
*) exit 1 ;;
esac

for pid in $(pstree -p "$ACTIVE_WINDOW_PID" -T | sed -E 's/-*([a-zA-Z0-9]+)\(([0-9]+)\)/\1 \2\n/g' | grep ^nvim | cut -d' ' -f2); do
	pid=$(pgrep -P "$pid" -f 'nvim --embed' || echo "$pid")
	nvim --server "$XDG_RUNTIME_DIR/nvim.$pid.0" --remote-expr "nvim_exec2('lua require(\"winnav\").nav(\"$DIRECTION\")', {})" >/dev/null 2>&1
	exit 0
done

$FOCUS "$1"
